name = "SparseQuadrature"
uuid = "7304c03a-8850-446d-9145-3faedd36b2b6"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
MultiIndexing = "b97ecbdf-1535-430e-a7c7-b5702749f368"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
