name = "SparseQuadrature"
uuid = "7304c03a-8850-446d-9145-3faedd36b2b6"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
